from pyspark.sql.types import StructType, StructField, StringType, BooleanType, TimestampType, DoubleType, IntegerType

# Define schema for JSON data
customers_schema = StructType([
    StructField("Customer ID", StringType(), nullable=False),
    StructField("Last Used Platform", StringType(), nullable=False),
    StructField("Is Blocked", BooleanType(), nullable=False),
    StructField("Created At", StringType(), nullable=False),
    StructField("Language", StringType(), nullable=False),
    StructField("Outstanding Amount", DoubleType(), nullable=False),
    StructField("Loyalty Points", IntegerType(), nullable=False),
    StructField("Number of employees", IntegerType(), nullable=True),
])



orders_schema = StructType([
    StructField("Order ID", StringType(), nullable=True),
    StructField("Order Status", StringType(), nullable=True),
    StructField("Category Name", StringType(), nullable=True),
    StructField("SKU", StringType(), nullable=True),
    StructField("Customization Group", StringType(), nullable=True),
    StructField("Customization Option", StringType(), nullable=True),
    StructField("Quantity", IntegerType(), nullable=True),
    StructField("Unit Price", DoubleType(), nullable=True),
    StructField("Cost Price", DoubleType(), nullable=True),
    StructField("Total Cost Price", DoubleType(), nullable=True),
    StructField("Total Price", DoubleType(), nullable=True),
    StructField("Order Total", DoubleType(), nullable=True),
    StructField("Sub Total", DoubleType(), nullable=True),
    StructField("Tax", DoubleType(), nullable=True),
    StructField("Delivery Charge", DoubleType(), nullable=True),
    StructField("Tip", DoubleType(), nullable=True),
    StructField("Discount", DoubleType(), nullable=True),
    StructField("Remaining Balance", DoubleType(), nullable=True),
    StructField("Payment Method", StringType(), nullable=True),
    StructField("Additional Charge", DoubleType(), nullable=True),
    StructField("Taxable Amount", DoubleType(), nullable=True),
    StructField("Transaction ID", StringType(), nullable=True),
    StructField("Currency Symbol", StringType(), nullable=True),
    StructField("Transaction Status", StringType(), nullable=True),
    StructField("Promo Code", StringType(), nullable=True),
    StructField("Customer ID", StringType(), nullable=True),
    StructField("Merchant ID", StringType(), nullable=True),
    StructField("Description", StringType(), nullable=True),
    StructField("Distance (in km)", DoubleType(), nullable=True),
    StructField("Order Time", TimestampType(), nullable=True),
    StructField("Pickup Time", TimestampType(), nullable=True),
    StructField("Delivery Time", TimestampType(), nullable=True),
    StructField("Ratings", IntegerType(), nullable=True),
    StructField("Reviews", StringType(), nullable=True),
    StructField("Merchant Earning", DoubleType(), nullable=True),
    StructField("Commission Amount", DoubleType(), nullable=True),
    StructField("Commission Payout Status", StringType(), nullable=True),
    StructField("Order Preparation Time", IntegerType(), nullable=True),
    StructField("Debt Amount", DoubleType(), nullable=True),
    StructField("Redeemed Loyalty Points", IntegerType(), nullable=True),
    StructField("Consumed Loyalty Points", IntegerType(), nullable=True),
    StructField("Cancellation Reason", StringType(), nullable=True),
    StructField("Flat Discount", DoubleType(), nullable=True),
    StructField("Checkout Template Name", StringType(), nullable=True),
    StructField("Checkout Template Value", StringType(), nullable=True)
])


deliveries_schema = StructType([
    StructField("Task_ID", StringType(), nullable=True),
    StructField("Order_ID", StringType(), nullable=True),
    StructField("Relationship", StringType(), nullable=True),
    StructField("Team_Name", StringType(), nullable=True),
    StructField("Task_Type", StringType(), nullable=True),
    StructField("Notes", StringType(), nullable=True),
    StructField("Agent_ID", StringType(), nullable=True),
    StructField("Agent_Name", StringType(), nullable=True),
    StructField("Distance(m)", DoubleType(), nullable=True),
    StructField("Total_Time_Taken(min)", DoubleType(), nullable=True),
    StructField("Task_Status", StringType(), nullable=True),
    StructField("Ref_Images", StringType(), nullable=True),
    StructField("Rating", IntegerType(), nullable=True),
    StructField("Review", StringType(), nullable=True),
    StructField("Latitude", DoubleType(), nullable=True),
    StructField("Longitude", DoubleType(), nullable=True),
    StructField("Tags", StringType(), nullable=True),
    StructField("Promo_Applied", StringType(), nullable=True),
    StructField("Custom_Template_ID", StringType(), nullable=True),
    StructField("Task_Details_QTY", IntegerType(), nullable=True),
    StructField("Task_Details_AMOUNT", DoubleType(), nullable=True),
    StructField("Special_Instructions", StringType(), nullable=True),
    StructField("Tip", DoubleType(), nullable=True),
    StructField("Delivery_Charges", DoubleType(), nullable=True),
    StructField("Discount", DoubleType(), nullable=True),
    StructField("Subtotal", DoubleType(), nullable=True),
    StructField("Payment_Type", StringType(), nullable=True),
    StructField("Task_Category", StringType(), nullable=True),
    StructField("Earning", DoubleType(), nullable=True),
    StructField("Pricing", StringType(), nullable=True)
])



customers_schema_sql = """CREATE TABLE customers (
                        `Customer ID` VARCHAR(255) NOT NULL,
                        `Last Used Platform` VARCHAR(255) NOT NULL,
                        `Is Blocked` BOOLEAN NOT NULL,
                        `Created At` VARCHAR(255) NOT NULL,
                        `Language` VARCHAR(255) NOT NULL,
                        `Outstanding Amount` DOUBLE NOT NULL,
                        `Loyalty Points` INT NOT NULL,
                        `Number of employees` INT
                    );
                    """
                    
orders_schema_sql = """CREATE TABLE orders (
                        `Order ID` VARCHAR(255),
                        `Order Status` VARCHAR(255),
                        `Category Name` VARCHAR(255),
                        `SKU` VARCHAR(255),
                        `Customization Group` VARCHAR(255),
                        `Customization Option` VARCHAR(255),
                        `Quantity` INT,
                        `Unit Price` DOUBLE,
                        `Cost Price` DOUBLE,
                        `Total Cost Price` DOUBLE,
                        `Total Price` DOUBLE,
                        `Order Total` DOUBLE,
                        `Sub Total` DOUBLE,
                        `Tax` DOUBLE,
                        `Delivery Charge` DOUBLE,
                        `Tip` DOUBLE,
                        `Discount` DOUBLE,
                        `Remaining Balance` DOUBLE,
                        `Payment Method` VARCHAR(255),
                        `Additional Charge` DOUBLE,
                        `Taxable Amount` DOUBLE,
                        `Transaction ID` VARCHAR(255),
                        `Currency Symbol` VARCHAR(255),
                        `Transaction Status` VARCHAR(255),
                        `Promo Code` VARCHAR(255),
                        `Customer ID` VARCHAR(255),
                        `Merchant ID` VARCHAR(255),
                        `Description` VARCHAR(255),
                        `Distance (in km)` DOUBLE,
                        `Order Time` TIMESTAMP,
                        `Pickup Time` TIMESTAMP,
                        `Delivery Time` TIMESTAMP,
                        `Ratings` INT,
                        `Reviews` TEXT,
                        `Merchant Earning` DOUBLE,
                        `Commission Amount` DOUBLE,
                        `Commission Payout Status` VARCHAR(255),
                        `Order Preparation Time` INT,
                        `Debt Amount` DOUBLE,
                        `Redeemed Loyalty Points` INT,
                        `Consumed Loyalty Points` INT,
                        `Cancellation Reason` VARCHAR(255),
                        `Flat Discount` DOUBLE,
                        `Checkout Template Name` VARCHAR(255),
                        `Checkout Template Value` VARCHAR(255)
                    );
                    """
                    

deliveries_schema_sql = """CREATE TABLE deliveries (
                            `Task_ID` VARCHAR(255),
                            `Order_ID` VARCHAR(255),
                            `Relationship` VARCHAR(255),
                            `Team_Name` VARCHAR(255),
                            `Task_Type` VARCHAR(255),
                            `Notes` VARCHAR(255),
                            `Agent_ID` VARCHAR(255),
                            `Agent_Name` VARCHAR(255),
                            `Distance(m)` DOUBLE,
                            `Total_Time_Taken(min)` DOUBLE,
                            `Task_Status` VARCHAR(255),
                            `Ref_Images` VARCHAR(255),
                            `Rating` INT,
                            `Review` TEXT,
                            `Latitude` DOUBLE,
                            `Longitude` DOUBLE,
                            `Tags` VARCHAR(255),
                            `Promo_Applied` VARCHAR(255),
                            `Custom_Template_ID` VARCHAR(255),
                            `Task_Details_QTY` INT,
                            `Task_Details_AMOUNT` DOUBLE,
                            `Special_Instructions` VARCHAR(255),
                            `Tip` DOUBLE,
                            `Delivery_Charges` DOUBLE,
                            `Discount` DOUBLE,
                            `Subtotal` DOUBLE,
                            `Payment_Type` VARCHAR(255),
                            `Task_Category` VARCHAR(255),
                            `Earning` DOUBLE,
                            `Pricing` VARCHAR(255)
                        );
                        """